export const ACLConstants = {    
        //Modulo de Auditoria
        IDAuditoria:                                               '/auditoria',
        IDAuditoria_GENERAR_PROTOCOLO:                             '/auditoriaGENERAR_PROTOCOLO',        
        /*No Conformidad*/
        IDNoConformidad:                                           '/noconformidad',
        IDNoConformidad_GENERAR_PROTOCOLO:                         '/noconformidadGENERAR_PROTOCOLO',
        /*Capacitación */
        IDCapacitacion:                                            '/capacitacion',
        IDCapacitacion_GENERAR_PROTOCOLO:                          '/capacitacionGENERAR_PROTOCOLO',
        /*Mantenimiento */
        IDMantenimiento:                                           '/mantenimiento',
        IDMantenimiento_GENERAR_PROTOCOLO :                        '/mantenimientoGENERAR_PROTOCOLO',
        ID:                                                         '/informacion-documentada',
        ID_CREAR:                                                   '/informacion-documentadaCREAR',
        ID_VISUALIZAR:                                              '/informacion-documentadaVISUALIZAR',                              
        ID_GENERAR_PROTOCOLO:                                       '/informacion-documentadaGENERAR_PROTOCOLO',
        ID_MODIFICAR:                                               '/informacion-documentadaMODIFICAR', 
        ID_EXPORTAR:                                                '/informacion-documentadaEXPORTAR', 
        ID_DESBLOQUEAR:                                             '/informacion-documentadaDESBLOQUEAR', 
        ID_ACTIVAR:                                                 '/informacion-documentadaACTIVAR', 
        ID_BUSCAR:                                                  '/informacion-documentadaBUSCAR', 
        ID_DETALLE:                                                 '/informacion-documentada/busqueda/detalle',
        ID_DETALLE_CREAR:                                           '/informacion-documentada/busqueda/detalleCREAR',
        //cguerra
        ID_DETALLE_ACTIVAR:                                           '/informacion-documentada/busqueda/detalleACTIVAR',
        ID_DETALLE_MODIFICAR:                                           '/informacion-documentada/busqueda/detalleMODIFICAR',
        //cguerra
        ID_DETALLE_VISUALIZAR:                                      '/informacion-documentada/busqueda/detalleVISUALIZAR',

        ID_DETALLE_Elaboracion:                         '/informacion-documentada/busqueda/detalle/elaboracion',
        ID_DETALLE_Elaboracion_CREAR:                   '/informacion-documentada/busqueda/detalle/elaboracionCREAR',
        ID_DETALLE_Elaboracion_MODIFICAR:               '/informacion-documentada/busqueda/detalle/elaboracionMODIFICAR',
        ID_DETALLE_Elaboracion_ELIMINAR:                '/informacion-documentada/busqueda/detalle/elaboracionELIMINAR',

        ID_DETALLE_Consenso:                            '/informacion-documentada/busqueda/detalle/consenso',
        ID_DETALLE_Consenso_CREAR:                      '/informacion-documentada/busqueda/detalle/consensoCREAR',     
        ID_DETALLE_Consenso_MODIFICAR:                  '/informacion-documentada/busqueda/detalle/consensoMODIFICAR',
        ID_DETALLE_Consenso_ELIMINAR:                   '/informacion-documentada/busqueda/detalle/consensoELIMINAR',

        ID_DETALLE_Aprobacion:                          '/informacion-documentada/busqueda/detalle/aprobacion',
        ID_DETALLE_Aprobacion_CREAR:                    '/informacion-documentada/busqueda/detalle/aprobacionCREAR' ,
        ID_DETALLE_Aprobacion_MODIFICAR:                '/informacion-documentada/busqueda/detalle/aprobacionMODIFICAR',
        ID_DETALLE_Aprobacion_ELIMINAR:                 '/informacion-documentada/busqueda/detalle/aprobacionELIMINAR',

        ID_DETALLE_Homologacion:                        '/informacion-documentada/busqueda/detalle/homologacion',
        ID_DETALLE_Homologacion_CREAR:                  '/informacion-documentada/busqueda/detalle/homologacionCREAR',
        ID_DETALLE_Homologacion_MODIFICAR:              '/informacion-documentada/busqueda/detalle/homologacionMODIFICAR',
        ID_DETALLE_Homologacion_ELIMINAR:               '/informacion-documentada/busqueda/detalle/homologacionELIMINAR',

        ID_DETALLE_Documentos_Relacionados:             '/informacion-documentada/busqueda/detalle/documentos-relacionados',
        ID_DETALLE_Documentos_Relacionados_CREAR:       '/informacion-documentada/busqueda/detalle/documentos-relacionadosCREAR',
        ID_DETALLE_Documentos_Relacionados_VISUALIZAR:  '/informacion-documentada/busqueda/detalle/documentos-relacionadosVISUALIZAR',
        ID_DETALLE_Documentos_Relacionados_ELIMINAR:    '/informacion-documentada/busqueda/detalle/documentos-relacionadosELIMINAR',
                    

        ID_DETALLE_Equipo_Usuario:                      '/informacion-documentada/busqueda/detalle/equipo-usuario',
        ID_DETALLE_Equipo_Usuario_CREAR:                '/informacion-documentada/busqueda/detalle/equipo-usuarioCREAR',
        ID_DETALLE_Equipo_Usuario_ELIMINAR:             '/informacion-documentada/busqueda/detalle/equipo-usuarioELIMINAR',

        ID_DETALLE_Revisiones:                          '/informacion-documentada/busqueda/detalle/revisiones',
        ID_DETALLE_Revisiones_VISUALIZAR:               '/informacion-documentada/busqueda/detalle/revisionesVISUALIZAR',

        ID_DOC:                                         '/informacion-documentada/documentos',
        ID_DOC_ConsultaGeneral:                         '/informacion-documentada/documentos/consulta-general',
        ID_DOC_ConsultaGeneral_ACTIVAR:                 '/informacion-documentada/documentos/consulta-generalACTIVAR',
        ID_DOC_ConsultaGeneral_BUSCAR:                  '/informacion-documentada/documentos/consulta-generalBUSCAR',
        ID_DOC_ConsultaGeneral_DESBLOQUEAR:             '/informacion-documentada/documentos/consulta-generalDESBLOQUEAR',
        ID_DOC_ConsultaGeneral_CREAR:                   '/informacion-documentada/documentos/consulta-generalCREAR',
        ID_DOC_ConsultaGeneral_EXPORTAR:                '/informacion-documentada/documentos/consulta-generalEXPORTAR',
        ID_DOC_ConsultaGeneral_MODIFICAR:               '/informacion-documentada/documentos/consulta-generalMODIFICAR',
        ID_DOC_ConsultaGeneral_VISUALIZAR:              '/informacion-documentada/documentos/consulta-generalVISUALIZAR',

        ID_DOC_ConsultaGeneral_Detalle:                 '/informacion-documentada/documentos/consulta-general/detalle',
        ID_DOC_ConsultaGeneral_Detalle_CREAR:           '/informacion-documentada/documentos/consulta-general/detalleCREAR',
        ID_DOC_ConsultaGeneral_Detalle_MODIFICAR:           '/informacion-documentada/documentos/consulta-general/detalleMODIFICAR',
        ID_DOC_ConsultaGeneral_Detalle_VISUALIZAR:      '/informacion-documentada/documentos/consulta-general/detalleVISUALIZAR',

        ID_DOC_ConsultaGeneral_Elaboracion:             '/informacion-documentada/documentos/consulta-general/detalle/elaboracion',
        ID_DOC_ConsultaGeneral_Elaboracion_CREAR:       '/informacion-documentada/documentos/consulta-general/detalle/elaboracionCREAR',
        ID_DOC_ConsultaGeneral_Elaboracion_MODIFICAR:   '/informacion-documentada/documentos/consulta-general/detalle/elaboracionMODIFICAR',
        ID_DOC_ConsultaGeneral_Elaboracion_ELIMINAR:    '/informacion-documentada/documentos/consulta-general/detalle/elaboracionELIMINAR',

        ID_DOC_ConsultaGeneral_Consenso:                '/informacion-documentada/documentos/consulta-general/detalle/consenso',
        ID_DOC_ConsultaGeneral_Consenso_CREAR:          '/informacion-documentada/documentos/consulta-general/detalle/consensoCREAR',
        ID_DOC_ConsultaGeneral_Consenso_MODIFICAR:      '/informacion-documentada/documentos/consulta-general/detalle/consensoMODIFICAR',
        ID_DOC_ConsultaGeneral_Consenso_ELIMINAR:       '/informacion-documentada/documentos/consulta-general/detalle/consensoELIMINAR',

        ID_DOC_ConsultaGeneral_Aprobacion:              '/informacion-documentada/documentos/consulta-general/detalle/aprobacion',
        ID_DOC_ConsultaGeneral_Aprobacion_CREAR:        '/informacion-documentada/documentos/consulta-general/detalle/aprobacionCREAR',
        ID_DOC_ConsultaGeneral_Aprobacion_MODIFICAR:    '/informacion-documentada/documentos/consulta-general/detalle/aprobacionMODIFICAR',
        ID_DOC_ConsultaGeneral_Aprobacion_ELIMINAR:     '/informacion-documentada/documentos/consulta-general/detalle/aprobacionELIMINAR',

        ID_DOC_ConsultaGeneral_Homologacion:            '/informacion-documentada/documentos/consulta-general/detalle/homologacion',
        ID_DOC_ConsultaGeneral_Homologacion_CREAR:      '/informacion-documentada/documentos/consulta-general/detalle/homologacionCREAR',
        ID_DOC_ConsultaGeneral_Homologacion_MODIFICAR:  '/informacion-documentada/documentos/consulta-general/detalle/homologacionMODIFICAR',
        ID_DOC_ConsultaGeneral_Homologacion_ELIMINAR:   '/informacion-documentada/documentos/consulta-general/detalle/homologacionELIMINAR',

        ID_DOC_ConsultaGeneral_Doc_Rela:                '/informacion-documentada/documentos/consulta-general/detalle/documentos-relacionados',
        ID_DOC_ConsultaGeneral_Doc_Rela_CREAR:          '/informacion-documentada/documentos/consulta-general/detalle/documentos-relacionadosCREAR',
        ID_DOC_ConsultaGeneral_Doc_Rela_VISUALIZAR:     '/informacion-documentada/documentos/consulta-general/detalle/documentos-relacionadosVISUALIZAR',
        ID_DOC_ConsultaGeneral_Doc_Rela_ELIMINAR:       '/informacion-documentada/documentos/consulta-general/detalle/documentos-relacionadosELIMINAR',

        ID_DOC_ConsultaGeneral_Equipo_Usuario:          '/informacion-documentada/documentos/consulta-general/detalle/equipo-usuario',
        ID_DOC_ConsultaGeneral_Equipo_Usuario_CREAR:    '/informacion-documentada/documentos/consulta-general/detalle/equipo-usuarioCREAR',
        ID_DOC_ConsultaGeneral_Equipo_Usuario_ELIMINAR: '/informacion-documentada/documentos/consulta-general/detalle/equipo-usuarioELIMINAR',

        ID_DOC_ConsultaGeneral_Revisiones:              '/informacion-documentada/documentos/consulta-general/detalle/revisiones',
        ID_DOC_ConsultaGeneral_Revisiones_VISUALIZAR:   '/informacion-documentada/documentos/consulta-general/detalle/revisionesVISUALIZAR',

        ID_DOC_ConsultaJerarquia:                       '/informacion-documentada/documentos/consulta-jerarquia',
        ID_DOC_ConsultaJerarquia_ACTIVAR:               '/informacion-documentada/documentos/consulta-jerarquiaACTIVAR',
        ID_DOC_ConsultaJerarquia_BUSCAR:                '/informacion-documentada/documentos/consulta-jerarquiaBUSCAR',
        ID_DOC_ConsultaJerarquia_CREAR:                 '/informacion-documentada/documentos/consulta-jerarquiaCREAR',
        ID_DOC_ConsultaJerarquia_DESBLOQUEAR:           '/informacion-documentada/documentos/consulta-jerarquiaDESBLOQUEAR',
        ID_DOC_ConsultaJerarquia_EXPORTAR:              '/informacion-documentada/documentos/consulta-jerarquiaEXPORTAR',
        ID_DOC_ConsultaJerarquia_MODIFICAR:             '/informacion-documentada/documentos/consulta-jerarquiaMODIFICAR',
        ID_DOC_ConsultaJerarquia_VISUALIZAR:            '/informacion-documentada/documentos/consulta-jerarquiaVISUALIZAR',

        ID_DOC_ConsultaJerarquia_Detalle:               '/informacion-documentada/documentos/consulta-jerarquia/detalle',
        ID_DOC_ConsultaJerarquia_Detalle_CREAR:         '/informacion-documentada/documentos/consulta-jerarquia/detalleCREAR',
        ID_DOC_ConsultaJerarquia_Detalle_ACTIVAR:       '/informacion-documentada/documentos/consulta-jerarquia/detalleACTIVAR',
        ID_DOC_ConsultaJerarquia_Detalle_MODIFICAR:     '/informacion-documentada/documentos/consulta-jerarquia/detalleMODIFICAR',
        ID_DOC_ConsultaJerarquia_Detalle_VISUALIZAR:    '/informacion-documentada/documentos/consulta-jerarquia/detalleVISUALIZAR',

        ID_DOC_ConsultaJerarquia_Elaboracion:           '/informacion-documentada/documentos/consulta-jerarquia/detalle/elaboracion',
        ID_DOC_ConsultaJerarquia_Elaboracion_CREAR:     '/informacion-documentada/documentos/consulta-jerarquia/detalle/elaboracionCREAR',
        ID_DOC_ConsultaJerarquia_Elaboracion_MODIFICAR: '/informacion-documentada/documentos/consulta-jerarquia/detalle/elaboracionMODIFICAR',
        ID_DOC_ConsultaJerarquia_Elaboracion_ELIMINAR:  '/informacion-documentada/documentos/consulta-jerarquia/detalle/elaboracionELIMINAR',

        ID_DOC_ConsultaJerarquia_Consenso:              '/informacion-documentada/documentos/consulta-jerarquia/detalle/consenso',
        ID_DOC_ConsultaJerarquia_Consenso_CREAR:        '/informacion-documentada/documentos/consulta-jerarquia/detalle/consensoCREAR',
        ID_DOC_ConsultaJerarquia_Consenso_MODIFICAR:    '/informacion-documentada/documentos/consulta-jerarquia/detalle/consensoMODIFICAR',
        ID_DOC_ConsultaJerarquia_Consenso_ELIMINAR:     '/informacion-documentada/documentos/consulta-jerarquia/detalle/consensoELIMINAR',

        ID_DOC_ConsultaJerarquia_Aprobacion:            '/informacion-documentada/documentos/consulta-jerarquia/detalle/aprobacion',
        ID_DOC_ConsultaJerarquia_Aprobacion_CREAR:      '/informacion-documentada/documentos/consulta-jerarquia/detalle/aprobacionCREAR',
        ID_DOC_ConsultaJerarquia_Aprobacion_MODIFICAR:  '/informacion-documentada/documentos/consulta-jerarquia/detalle/aprobacionMODIFICAR',
        ID_DOC_ConsultaJerarquia_Aprobacion_ELIMINAR:   '/informacion-documentada/documentos/consulta-jerarquia/detalle/aprobacionELIMINAR',

        ID_DOC_ConsultaJerarquia_Homologacion:               '/informacion-documentada/documentos/consulta-jerarquia/detalle/homologacion',
        ID_DOC_ConsultaJerarquia_Homologacion_CREAR:         '/informacion-documentada/documentos/consulta-jerarquia/detalle/homologacionCREAR',    
        ID_DOC_ConsultaJerarquia_Homologacion_MODIFICAR:     '/informacion-documentada/documentos/consulta-jerarquia/detalle/homologacionMODIFICAR',
        ID_DOC_ConsultaJerarquia_Homologacion_ELIMINAR:      '/informacion-documentada/documentos/consulta-jerarquia/detalle/homologacionELIMINAR',

        ID_DOC_ConsultaJerarquia_Doc_Rela:              '/informacion-documentada/documentos/consulta-jerarquia/detalle/documentos-relacionados',
        ID_DOC_ConsultaJerarquia_Doc_Rela_CREAR:        '/informacion-documentada/documentos/consulta-jerarquia/detalle/documentos-relacionadosCREAR',
        ID_DOC_ConsultaJerarquia_Doc_Rela_VISUALIZAR:   '/informacion-documentada/documentos/consulta-jerarquia/detalle/documentos-relacionadosVISUALIZAR',
        ID_DOC_ConsultaJerarquia_Doc_Rela_ELIMINAR:      '/informacion-documentada/documentos/consulta-jerarquia/detalle/documentos-relacionadosELIMINAR',

        ID_DOC_ConsultaJerarquia_Equipo_Usuario:            '/informacion-documentada/documentos/consulta-jerarquia/detalle/equipo-usuario',
        ID_DOC_ConsultaJerarquia_Equipo_Usuario_CREAR:      '/informacion-documentada/documentos/consulta-jerarquia/detalle/equipo-usuarioCREAR',
        ID_DOC_ConsultaJerarquia_Equipo_Usuario_ELIMINAR:   '/informacion-documentada/documentos/consulta-jerarquia/detalle/equipo-usuarioELIMINAR',

        ID_DOC_ConsultaJerarquia_Revision:              '/informacion-documentada/documentos/consulta-jerarquia/detalle/revisiones',
        ID_DOC_ConsultaJerarquia_Revision_VISUALIZAR:   '/informacion-documentada/documentos/consulta-jerarquia/detalle/revisionesVISUALIZAR',

        ID_SOL:                                         '/informacion-documentada/solicitudes',
        ID_SOL_SolicitudCancelacion:                    '/informacion-documentada/solicitudes/solicitud-cancelacion',
        ID_SOL_SolicitudCancelacion_BUSCAR:             '/informacion-documentada/solicitudes/solicitud-cancelacionBUSCAR',
        ID_SOL_SolicitudCancelacion_CREAR:              '/informacion-documentada/solicitudes/solicitud-cancelacionCREAR',
        ID_SOL_SolicitudCancelacion_MODIFICAR:          '/informacion-documentada/solicitudes/solicitud-cancelacionMODIFICAR',
        ID_SOL_SolicitudCancelacion_VISUALIZAR:         '/informacion-documentada/solicitudes/solicitud-cancelacionVISUALIZAR',
        ID_SOL_SolicitudCopiasImpresas:                 '/informacion-documentada/solicitudes/solicitud-copias-impresas',
        ID_SOL_SolicitudCopiasImpresas_BUSCAR:          '/informacion-documentada/solicitudes/solicitud-copias-impresasBUSCAR',
        ID_SOL_SolicitudCopiasImpresas_CREAR:           '/informacion-documentada/solicitudes/solicitud-copias-impresasCREAR',
        ID_SOL_SolicitudCopiasImpresas_MODIFICAR:       '/informacion-documentada/solicitudes/solicitud-copias-impresasMODIFICAR',
        ID_SOL_SolicitudRevision:                       '/informacion-documentada/solicitudes/solicitud-revision',
        ID_SOL_SolicitudRevision_BUSCAR:                '/informacion-documentada/solicitudes/solicitud-revisionBUSCAR',
        ID_SOL_SolicitudRevision_CREAR:                 '/informacion-documentada/solicitudes/solicitud-revisionCREAR',
        ID_SOL_SolicitudRevision_ELIMINAR:              '/informacion-documentada/solicitudes/solicitud-revisionELIMINAR',
        ID_SOL_SolicitudRevision_MODIFICAR:             '/informacion-documentada/solicitudes/solicitud-revisionMODIFICAR',
        ID_SOL_SolicitudRevision_VISUALIZAR:            '/informacion-documentada/solicitudes/solicitud-revisionVISUALIZAR',

        ID_TAR:                                         '/informacion-documentada/tareas',
        ID_TAR_Aprobacion:                              '/informacion-documentada/tareas/aprobacion',
        ID_TAR_Aprobacion_BUSCAR:                       '/informacion-documentada/tareas/aprobacionBUSCAR',
        ID_TAR_Aprobacion_MODIFICAR:                    '/informacion-documentada/tareas/aprobacionMODIFICAR',
        ID_TAR_AprobacionCancelacion:                   '/informacion-documentada/tareas/aprobacion-cancelacion',
        ID_TAR_AprobacionCancelacion_BUSCAR:            '/informacion-documentada/tareas/aprobacion-cancelacionBUSCAR',
        ID_TAR_AprobacionCancelacion_MODIFICAR:         '/informacion-documentada/tareas/aprobacion-cancelacionMODIFICAR',
        ID_TAR_AprobacionCancelacion_VISUALIZAR:        '/informacion-documentada/tareas/aprobacion-cancelacionVISUALIZAR',
        ID_TAR_AprobacionCopiasImpresas:                '/informacion-documentada/tareas/aprobacion-copias-impresas',
        ID_TAR_AprobacionCopiasImpresas_BUSCAR:         '/informacion-documentada/tareas/aprobacion-copias-impresasBUSCAR',
        ID_TAR_AprobacionCopiasImpresas_MODIFICAR:      '/informacion-documentada/tareas/aprobacion-copias-impresasMODIFICAR',
        ID_TAR_AprobacionSolicitudRevision:             '/informacion-documentada/tareas/aprobacion-solicitud-revision',
        ID_TAR_AprobacionSolicitudRevision_BUSCAR:      '/informacion-documentada/tareas/aprobacion-solicitud-revisionBUSCAR',
        ID_TAR_AprobacionSolicitudRevision_MODIFICAR:   '/informacion-documentada/tareas/aprobacion-solicitud-revisionMODIFICAR',
        ID_TAR_AprobacionSolicitudRevision_VISUALIZAR:  '/informacion-documentada/tareas/aprobacion-solicitud-revisionVISUALIZAR',
        ID_TAR_CancelacionDocumentos:                   '/informacion-documentada/tareas/cancelacion-documentos',
        ID_TAR_CancelacionDocumentos_BUSCAR:            '/informacion-documentada/tareas/cancelacion-documentosBUSCAR',
        ID_TAR_CancelacionDocumentos_MODIFICAR:         '/informacion-documentada/tareas/cancelacion-documentosMODIFICAR',
        ID_TAR_CancelacionDocumentos_VISUALIZAR:        '/informacion-documentada/tareas/cancelacion-documentosVISUALIZAR',
        ID_TAR_ConocimientoRevision:                    '/informacion-documentada/tareas/conocimiento-revision',
        ID_TAR_ConocimientoRevision_BUSCAR:             '/informacion-documentada/tareas/conocimiento-revisionBUSCAR',
        ID_TAR_ConocimientoRevision_VISUALIZAR:         '/informacion-documentada/tareas/conocimiento-revisionVISUALIZAR',
        ID_TAR_Consenso:                                '/informacion-documentada/tareas/consenso',
        ID_TAR_Consenso_BUSCAR:                         '/informacion-documentada/tareas/consensoBUSCAR',
        ID_TAR_Consenso_MODIFICAR:                      '/informacion-documentada/tareas/consensoMODIFICAR',
        ID_TAR_Elaboracion:                             '/informacion-documentada/tareas/elaboracion',
        ID_TAR_Elaboracion_BUSCAR:                      '/informacion-documentada/tareas/elaboracionBUSCAR',
        ID_TAR_Elaboracion_MODIFICAR:                   '/informacion-documentada/tareas/elaboracionMODIFICAR',
        ID_TAR_Homologacion:                            '/informacion-documentada/tareas/homologacion',
        ID_TAR_Homologacion_BUSCAR:                     '/informacion-documentada/tareas/homologacionBUSCAR',
        ID_TAR_Homologacion_MODIFICAR:                  '/informacion-documentada/tareas/homologacionMODIFICAR',

        ID_REV:                                         '/informacion-documentada/revision-actualizacion',
        ID_REV_DistribucionEjecucion:                   '/informacion-documentada/revision-actualizacion/distribucion-ejecucion',
        ID_REV_DistribucionEjecucion_BUSCAR:            '/informacion-documentada/revision-actualizacion/distribucion-ejecucionBUSCAR',
        ID_REV_DistribucionEjecucion_MODIFICAR:         '/informacion-documentada/revision-actualizacion/distribucion-ejecucionMODIFICAR',
        ID_REV_BandejaEjecucion:                        '/informacion-documentada/revision-actualizacion/bandeja-ejecucion',
        ID_REV_BandejaEjecucion_BUSCAR:                  '/informacion-documentada/revision-actualizacion/bandeja-ejecucionBUSCAR',
        ID_REV_Programacion:                            '/informacion-documentada/revision-actualizacion/programacion',
        ID_REV_Programacion_BUSCAR:                     '/informacion-documentada/revision-actualizacion/programacionBUSCAR',
        ID_REV_Programacion_CREAR:                      '/informacion-documentada/revision-actualizacion/programacionCREAR',
        ID_REV_Programacion_ELIMINAR:                   '/informacion-documentada/revision-actualizacion/programacionELIMINAR',
        ID_REV_Programacion_MODIFICAR:                  '/informacion-documentada/revision-actualizacion/programacionMODIFICAR',    

        ID_CON:                                         '/informacion-documentada/consulta',
        ID_CON_DescargaMasivaDocumentos:                '/informacion-documentada/consulta/descarga-masiva-documentos',
        ID_CON_DescargaMasivaDocumentos_VISUALIZAR:     '/informacion-documentada/consulta/descarga-masiva-documentosVISUALIZAR',
        ID_CON_DescargaVideosPlantillas:                '/informacion-documentada/consulta/descarga-videos-plantillas',
        ID_CON_DescargaVideosPlantillas_BUSCAR:         '/informacion-documentada/consulta/descarga-videos-plantillasBUSCAR',
        ID_CON_DescargaVideosPlantillas_CREAR:          '/informacion-documentada/consulta/descarga-videos-plantillasCREAR',
        ID_CON_DescargaVideosPlantillas_ELIMINAR:       '/informacion-documentada/consulta/descarga-videos-plantillasELIMINAR',
        ID_CON_DescargaVideosPlantillas_EXPORTAR:       '/informacion-documentada/consulta/descarga-videos-plantillasEXPORTAR',
        ID_CON_ReporteConocimientoRevision:             '/informacion-documentada/consulta/reporte-conocimiento-revision',
        ID_CON_ReporteConocimientoRevision_VISUALIZAR:  '/informacion-documentada/consulta/reporte-conocimiento-revisionVISUALIZAR',
        ID_CON_ReporteDocumentosCancelados:             '/informacion-documentada/consulta/reporte-documentos-cancelados',
        ID_CON_ReporteDocumentosCancelados_VISUALIZAR:  '/informacion-documentada/consulta/reporte-documentos-canceladosVISUALIZAR',
        ID_CON_ReporteTransaccionDocumentos:            '/informacion-documentada/consulta/reporte-transaccion-documentos',
        ID_CON_ReporteTransaccionDocumentos_VISUALIZAR: '/informacion-documentada/consulta/reporte-transaccion-documentosVISUALIZAR',
        ID_CON_SeguimientoDocumento:                    '/informacion-documentada/consulta/seguimiento-documento',
        ID_CON_SeguimientoDocumento_VISUALIZAR:         '/informacion-documentada/consulta/seguimiento-documentoVISUALIZAR',
        //Cguerra
        ID_CON_ConocimientoRevisionDocumento_VISUALIZAR:  '/informacion-documentada/consulta/conocimiento-revision-documentosVISUALIZAR' , 
        ID_CON_ConocimientoRevisionDocumento_BUSCAR:      '/informacion-documentada/consulta/conocimiento-revision-documentosBUSCAR',
        ID_CON_ConocimientoRevisionDocumento:             '/informacion-documentada/consulta/conocimiento-revision-documentos',

        ID_SOL_SolicitudRevision_Detalle:                       '/informacion-documentada/solicitudes/solicitud-revision/detalle',
        ID_SOL_SolicitudRevision_Detalle_VISUALIZAR:            '/informacion-documentada/solicitudes/solicitud-revision/detalleVISUALIZAR',
        ID_SOL_SolicitudRevision_Detalle_CREAR:                 '/informacion-documentada/solicitudes/solicitud-revision/detalleCREAR',
        ID_SOL_SolicitudRevision_Detalle_BUSCAR:                '/informacion-documentada/solicitudes/solicitud-revision/detalleBUSCAR',
        ID_SOL_SolicitudRevision_Detalle_Elaboracion:           '/informacion-documentada/solicitudes/solicitud-revision/detalle/elaboracion',
        ID_SOL_SolicitudRevision_Detalle_Elaboracion_CREAR:     '/informacion-documentada/solicitudes/solicitud-revision/detalle/elaboracionCREAR',
        ID_SOL_SolicitudRevision_Detalle_Elaboracion_MODIFICAR: '/informacion-documentada/solicitudes/solicitud-revision/detalle/elaboracionMODIFICAR',
        ID_SOL_SolicitudRevision_Detalle_Elaboracion_ELIMINAR:  '/informacion-documentada/solicitudes/solicitud-revision/detalle/elaboracionELIMINAR',
        ID_SOL_SolicitudRevision_Detalle_Consenso:              '/informacion-documentada/solicitudes/solicitud-revision/detalle/consenso',
        ID_SOL_SolicitudRevision_Detalle_Consenso_CREAR:        '/informacion-documentada/solicitudes/solicitud-revision/detalle/consensoCREAR',
        ID_SOL_SolicitudRevision_Detalle_Consenso_MODIFICAR:    '/informacion-documentada/solicitudes/solicitud-revision/detalle/consensoMODIFICAR',
        ID_SOL_SolicitudRevision_Detalle_Consenso_ELIMINAR:     '/informacion-documentada/solicitudes/solicitud-revision/detalle/consensoELIMINAR',
        ID_SOL_SolicitudRevision_Detalle_Aprobacion:            '/informacion-documentada/solicitudes/solicitud-revision/detalle/aprobacion',
        ID_SOL_SolicitudRevision_Detalle_Aprobacion_CREAR:      '/informacion-documentada/solicitudes/solicitud-revision/detalle/aprobacionCREAR',
        ID_SOL_SolicitudRevision_Detalle_Aprobacion_MODIFICAR:  '/informacion-documentada/solicitudes/solicitud-revision/detalle/aprobacionMODIFICAR',
        ID_SOL_SolicitudRevision_Detalle_Aprobacion_ELIMINAR:   '/informacion-documentada/solicitudes/solicitud-revision/detalle/aprobacionELIMINAR',
        ID_SOL_SolicitudRevision_Detalle_Homologacion:          '/informacion-documentada/solicitudes/solicitud-revision/detalle/homologacion',
        ID_SOL_SolicitudRevision_Detalle_Homologacion_CREAR:    '/informacion-documentada/solicitudes/solicitud-revision/detalle/homologacionCREAR',
        ID_SOL_SolicitudRevision_Detalle_Homologacion_MODIFICAR:'/informacion-documentada/solicitudes/solicitud-revision/detalle/homologacionMODIFICAR',
        ID_SOL_SolicitudRevision_Detalle_Homologacion_ELIMINAR: '/informacion-documentada/solicitudes/solicitud-revision/detalle/homologacionELIMINAR',
        ID_SOL_SolicitudRevision_Detalle_DocRela:               '/informacion-documentada/solicitudes/solicitud-revision/detalle/documentos-relacionados',
        ID_SOL_SolicitudRevision_Detalle_DocRela_CREAR:         '/informacion-documentada/solicitudes/solicitud-revision/detalle/documentos-relacionadosCREAR',
        ID_SOL_SolicitudRevision_Detalle_DocRela_VISUALIZAR:    '/informacion-documentada/solicitudes/solicitud-revision/detalle/documentos-relacionadosVISUALIZAR',
        ID_SOL_SolicitudRevision_Detalle_DocRela_ELIMINAR:      '/informacion-documentada/solicitudes/solicitud-revision/detalle/documentos-relacionadosELIMINAR',
        ID_SOL_SolicitudRevision_Detalle_EquipoUsuario:         '/informacion-documentada/solicitudes/solicitud-revision/detalle/equipo-usuario',
        ID_SOL_SolicitudRevision_Detalle_EquipoUsuario_CREAR:   '/informacion-documentada/solicitudes/solicitud-revision/detalle/equipo-usuarioCREAR',
        ID_SOL_SolicitudRevision_Detalle_EquipoUsuario_ELIMINAR:'/informacion-documentada/solicitudes/solicitud-revision/detalle/equipo-usuarioELIMINAR',
        ID_SOL_SolicitudRevision_Detalle_Revision:              '/informacion-documentada/solicitudes/solicitud-revision/detalle/revisiones',
        ID_SOL_SolicitudRevision_Detalle_Revision_VISUALIZAR:   '/informacion-documentada/solicitudes/solicitud-revision/detalle/revisionesVISUALIZAR',

        ID_CON_SeguimientoDocumento_Detalle:                    '/informacion-documentada/consulta/seguimiento-documento/detalle',
        ID_CON_SeguimientoDocumento_Detalle_VISUALIZAR:         '/informacion-documentada/consulta/seguimiento-documento/detalleVISUALIZAR',
        ID_CON_SeguimientoDocumento_Detalle_Elaboracion:        '/informacion-documentada/consulta/seguimiento-documento/detalle/elaboracion',
        ID_CON_SeguimientoDocumento_Detalle_Elaboracion_CREAR:  '/informacion-documentada/consulta/seguimiento-documento/detalle/elaboracionCREAR',
        ID_CON_SeguimientoDocumento_Detalle_Elaboracion_MODIFICAR:'/informacion-documentada/consulta/seguimiento-documento/detalle/elaboracionMODIFICAR',
        ID_CON_SeguimientoDocumento_Detalle_Elaboracion_ELIMINAR:'/informacion-documentada/consulta/seguimiento-documento/detalle/elaboracionELIMINAR',
        ID_CON_SeguimientoDocumento_Detalle_Consenso:           '/informacion-documentada/consulta/seguimiento-documento/detalle/consenso',
        ID_CON_SeguimientoDocumento_Detalle_Consenso_CREAR:     '/informacion-documentada/consulta/seguimiento-documento/detalle/consensoCREAR',
        ID_CON_SeguimientoDocumento_Detalle_Consenso_MODIFICAR: '/informacion-documentada/consulta/seguimiento-documento/detalle/consensoMODIFICAR',
        ID_CON_SeguimientoDocumento_Detalle_Consenso_ELIMINAR:  '/informacion-documentada/consulta/seguimiento-documento/detalle/consensoELIMINAR',
        ID_CON_SeguimientoDocumento_Detalle_Aprobacion:         '/informacion-documentada/consulta/seguimiento-documento/detalle/aprobacion',
        ID_CON_SeguimientoDocumento_Detalle_Aprobacion_CREAR:   '/informacion-documentada/consulta/seguimiento-documento/detalle/aprobacionCREAR',
        ID_CON_SeguimientoDocumento_Detalle_Aprobacion_MODIFICAR:'/informacion-documentada/consulta/seguimiento-documento/detalle/aprobacionMODIFICAR',
        ID_CON_SeguimientoDocumento_Detalle_Aprobacion_ELIMINAR:'/informacion-documentada/consulta/seguimiento-documento/detalle/aprobacionELIMINAR',
        ID_CON_SeguimientoDocumento_Detalle_Homologacion:       '/informacion-documentada/consulta/seguimiento-documento/detalle/homologacion',
        ID_CON_SeguimientoDocumento_Detalle_Homologacion_CREAR: '/informacion-documentada/consulta/seguimiento-documento/detalle/homologacionCREAR',
        ID_CON_SeguimientoDocumento_Detalle_Homologacion_MODIFICAR:'/informacion-documentada/consulta/seguimiento-documento/detalle/homologacionMODIFICAR',
        ID_CON_SeguimientoDocumento_Detalle_Homologacion_ELIMINAR:'/informacion-documentada/consulta/seguimiento-documento/detalle/homologacionELIMINAR',
        ID_CON_SeguimientoDocumento_Detalle_DocRela:            '/informacion-documentada/consulta/seguimiento-documento/detalle/documentos-relacionados',
        ID_CON_SeguimientoDocumento_Detalle_DocRela_CREAR:      '/informacion-documentada/consulta/seguimiento-documento/detalle/documentos-relacionadosCREAR',
        ID_CON_SeguimientoDocumento_Detalle_DocRela_VISUALIZAR: '/informacion-documentada/consulta/seguimiento-documento/detalle/documentos-relacionadosVISUALIZAR',
        ID_CON_SeguimientoDocumento_Detalle_DocRela_ELIMINAR:   '/informacion-documentada/consulta/seguimiento-documento/detalle/documentos-relacionadosELIMINAR',
        ID_CON_SeguimientoDocumento_Detalle_EquipoUsuario:      '/informacion-documentada/consulta/seguimiento-documento/detalle/equipo-usuario',
        ID_CON_SeguimientoDocumento_Detalle_EquipoUsuario_CREAR:'/informacion-documentada/consulta/seguimiento-documento/detalle/equipo-usuarioCREAR',
        ID_CON_SeguimientoDocumento_Detalle_EquipoUsuario_ELIMINAR:'/informacion-documentada/consulta/seguimiento-documento/detalle/equipo-usuarioELIMINAR',
        ID_CON_SeguimientoDocumento_Detalle_Revision:           '/informacion-documentada/consulta/seguimiento-documento/detalle/revisiones',
        ID_CON_SeguimientoDocumento_Detalle_Revision_VISUALIZAR:'/informacion-documentada/consulta/seguimiento-documento/detalle/revisionesVISUALIZAR',

        ID_SOL_SolicitudCancelacion_Detalle:                    '/informacion-documentada/solicitudes/solicitud-cancelacion/detalle',
        ID_SOL_SolicitudCancelacion_Detalle_CREAR:              '/informacion-documentada/solicitudes/solicitud-cancelacion/detalleCREAR',
        ID_SOL_SolicitudCancelacion_Detalle_VISUALIZAR:         '/informacion-documentada/solicitudes/solicitud-cancelacion/detalleVISUALIZAR',
        ID_SOL_SolicitudCancelacion_Detalle_DocRela:            '/informacion-documentada/solicitudes/solicitud-cancelacion/detalle/documentos-relacionados',                                                                
        ID_SOL_SolicitudCancelacion_Detalle_DocRela_VISUALIZAR: '/informacion-documentada/solicitudes/solicitud-cancelacion/detalle/documentos-relacionadosVISUALIZAR',
        ID_SOL_SolicitudCancelacion_Detalle_SustSoli:           '/informacion-documentada/solicitudes/solicitud-cancelacion/detalle/sustento-solicitudes',
        ID_SOL_SolicitudCancelacion_Detalle_SustSoli_EXPORTAR:  '/informacion-documentada/solicitudes/solicitud-cancelacion/detalle/sustento-solicitudesEXPORTAR',
        //Cguerra
        ID_SOL_SolicitudCopiasImpresas_Detalle:                    '/informacion-documentada/solicitudes/solicitud-copias-impresas/detalle',
        ID_SOL_SolicitudCopiasImpresas_Detalle_CREAR:              '/informacion-documentada/solicitudes/solicitud-copias-impresas/detalleCREAR',
        ID_SOL_SolicitudCopiasImpresas_Detalle_ELIMINAR:            '/informacion-documentada/solicitudes/solicitud-copias-impresas/detalleELIMINAR',
        ID_SOL_SolicitudCopiasImpresas_Detalle_Bitacora:            '/informacion-documentada/solicitudes/solicitud-copias-impresas/detalle/bitacora',
        ID_SOL_SolicitudCopiasImpresas_Detalle_Bitacora_VISUALIZAR: '/informacion-documentada/solicitudes/solicitud-copias-impresas/detalle/bitacoraVISUALIZAR',
        ID_TAR_Elaboracion_Detalle_documeRelac:                     '/informacion-documentada/tareas/elaboracion/detalle/documentos-relacionados',
        ID_TAR_Elaboracion_Detalle_documeRelac_CREAR:               '/informacion-documentada/tareas/elaboracion/detalle/documentos-relacionadosCREAR',
        ID_TAR_Elaboracion_Detalle_documeRelac_VISUALIZAR:          '/informacion-documentada/tareas/elaboracion/detalle/documentos-relacionadosVISUALIZAR',
        ID_TAR_Elaboracion_Detalle_documeRelac_ELIMINAR:            '/informacion-documentada/tareas/elaboracion/detalle/documentos-relacionadosELIMINAR',
        ID_TAR_Elaboracion_Detalle_EquipoUsua:                      '/informacion-documentada/tareas/elaboracion/detalle/equipo-usuario',
        ID_TAR_Elaboracion_Detalle_Equipo_Usuario_CREAR:            '/informacion-documentada/tareas/elaboracion/detalle/equipo-usuarioCREAR',
        ID_TAR_Elaboracion_Detalle_EquipoUsua_ELIMINAR:             '/informacion-documentada/tareas/elaboracion/detalle/equipo-usuarioELIMINAR',
        ID_TAR_Elaboracion_Detalle_Revision:                        '/informacion-documentada/tareas/elaboracion/detalle/revisiones',
        ID_TAR_Elaboracion_Detalle_Revision_VISUALIZAR:             '/informacion-documentada/tareas/elaboracion/detalle/revisionesVISUALIZAR',
        //cguerra
        ID_TAR_Elaboracion_Detalle:                             '/informacion-documentada/tareas/elaboracion/detalle',
        ID_TAR_Elaboracion_Detalle_CREAR:                       '/informacion-documentada/tareas/elaboracion/detalleCREAR',
        ID_TAR_Elaboracion_Detalle_VISUALIZAR:                  '/informacion-documentada/tareas/elaboracion/detalleVISUALIZAR',
        ID_TAR_Elaboracion_Detalle_Elaboracion:                 '/informacion-documentada/tareas/elaboracion/detalle/elaboracion',
        ID_TAR_Elaboracion_Detalle_Elaboracion_CREAR:           '/informacion-documentada/tareas/elaboracion/detalle/elaboracionCREAR',    
        ID_TAR_Elaboracion_Detalle_Elaboracion_MODIFICAR:       '/informacion-documentada/tareas/elaboracion/detalle/elaboracionMODIFICAR',
        ID_TAR_Elaboracion_Detalle_Elaboracion_VISUALIZAR:      '/informacion-documentada/tareas/elaboracion/detalle/elaboracionVISUALIZAR',
        ID_TAR_Elaboracion_Detalle_Elaboracion_ELIMINAR:        '/informacion-documentada/tareas/elaboracion/detalle/elaboracionELIMINAR',

        ID_TAR_Elaboracion_Detalle_Concenso:                    '/informacion-documentada/tareas/elaboracion/detalle/consenso',
        ID_TAR_Elaboracion_Detalle_Concenso_CREAR:              '/informacion-documentada/tareas/elaboracion/detalle/consensoCREAR',
        ID_TAR_Elaboracion_Detalle_Concenso_MODIFICAR:          '/informacion-documentada/tareas/elaboracion/detalle/consensoMODIFICAR',
        ID_TAR_Elaboracion_Detalle_Concenso_ELIMINAR:           '/informacion-documentada/tareas/elaboracion/detalle/consensoELIMINAR',

        ID_TAR_Elaboracion_Detalle_Aprobacion:                  '/informacion-documentada/tareas/elaboracion/detalle/aprobacion',
        ID_TAR_Elaboracion_Detalle_Aprobacion_CREAR:            '/informacion-documentada/tareas/elaboracion/detalle/aprobacionCREAR',
        ID_TAR_Elaboracion_Detalle_Aprobacion_MODIFICAR:        '/informacion-documentada/tareas/elaboracion/detalle/aprobacionMODIFICAR',
        ID_TAR_Elaboracion_Detalle_Aprobacion_ELIMINAR:         '/informacion-documentada/tareas/elaboracion/detalle/aprobacionELIMINAR',

        ID_TAR_Elaboracion_Detalle_Homologacion:                '/informacion-documentada/tareas/elaboracion/detalle/homologacion',
        ID_TAR_Elaboracion_Detalle_Homologacion_CREAR:          '/informacion-documentada/tareas/elaboracion/detalle/homologacionCREAR',
        ID_TAR_Elaboracion_Detalle_Homologacion_MODIFICAR:      '/informacion-documentada/tareas/elaboracion/detalle/homologacionMODIFICAR',
        ID_TAR_Elaboracion_Detalle_Homologacion_ELIMINAR:       '/informacion-documentada/tareas/elaboracion/detalle/homologacionELIMINAR',

        ID_TAR_Consenso_Detalle:                                '/informacion-documentada/tareas/consenso/detalle',
        ID_TAR_Consenso_Detalle_CREAR:                          '/informacion-documentada/tareas/consenso/detalleCREAR',
        ID_TAR_Consenso_Detalle_VISUALIZAR:                     '/informacion-documentada/tareas/consenso/detalleVISUALIZAR',
        ID_TAR_Consenso_Detalle_MODIFICAR:                      '/informacion-documentada/tareas/consenso/detalleMODIFICAR',
        ID_TAR_Consenso_Detalle_ELIMINAR:                       '/informacion-documentada/tareas/consenso/detalleELIMINAR',
        ID_TAR_Consenso_Detalle_Elaboracion:                    '/informacion-documentada/tareas/consenso/detalle/elaboracion',
        ID_TAR_Consenso_Detalle_Elaboracion_CREAR:              '/informacion-documentada/tareas/consenso/detalle/elaboracionCREAR',
        ID_TAR_Consenso_Detalle_Elaboracion_MODIFICAR:          '/informacion-documentada/tareas/consenso/detalle/elaboracionMODIFICAR',
        ID_TAR_Consenso_Detalle_Elaboracion_VISUALIZAR:         '/informacion-documentada/tareas/consenso/detalle/elaboracionVISUALIZAR',
        ID_TAR_Consenso_Detalle_Elaboracion_ELIMINAR:           '/informacion-documentada/tareas/consenso/detalle/elaboracionELIMINAR',

        ID_TAR_Consenso_Detalle_Concenso:                       '/informacion-documentada/tareas/consenso/detalle/consenso',
        ID_TAR_Consenso_Detalle_Concenso_CREAR:                 '/informacion-documentada/tareas/consenso/detalle/consensoCREAR',
        ID_TAR_Consenso_Detalle_Concenso_MODIFICAR:             '/informacion-documentada/tareas/consenso/detalle/consensoMODIFICAR',
        ID_TAR_Consenso_Detalle_Concenso_ELIMINAR:              '/informacion-documentada/tareas/consenso/detalle/consensoELIMINAR',

        ID_TAR_Consenso_Detalle_Aprobacion:                     '/informacion-documentada/tareas/consenso/detalle/aprobacion',
        ID_TAR_Consenso_Detalle_Aprobacion_CREAR:               '/informacion-documentada/tareas/consenso/detalle/aprobacionCREAR',
        ID_TAR_Consenso_Detalle_Aprobacion_MODIFICAR:           '/informacion-documentada/tareas/consenso/detalle/aprobacionMODIFICAR',
        ID_TAR_Consenso_Detalle_Aprobacion_ELIMINAR:            '/informacion-documentada/tareas/consenso/detalle/aprobacionELIMINAR',

        ID_TAR_Consenso_Detalle_Homologacion:                   '/informacion-documentada/tareas/consenso/detalle/homologacion',
        ID_TAR_Consenso_Detalle_Homologacion_CREAR:             '/informacion-documentada/tareas/consenso/detalle/homologacionCREAR',
        ID_TAR_Consenso_Detalle_Homologacion_MODIFICAR:         '/informacion-documentada/tareas/consenso/detalle/homologacionMODIFICAR',
        ID_TAR_Consenso_Detalle_Homologacion_ELIMINAR:          '/informacion-documentada/tareas/consenso/detalle/homologacionELIMINAR',

        ID_TAR_Concenso_Documento_Relacionado_Detalle:          '/informacion-documentada/tareas/consenso/detalle/documentos-relacionados',
        ID_TAR_Concenso_Documento_Relacionado_Detalle_CREAR:    '/informacion-documentada/tareas/consenso/detalle/documentos-relacionadosCREAR',
        ID_TAR_Concenso_Documento_Relacionado_Detalle_ELIMINAR: '/informacion-documentada/tareas/consenso/detalle/documentos-relacionadosELIMINAR',

        ID_TAR_Concenso_Equipo_Usuario_Detalle:                 '/informacion-documentada/tareas/consenso/detalle/equipo-usuario',
        ID_TAR_Concenso_Equipo_Usuario_Detalle_CREAR:           '/informacion-documentada/tareas/consenso/detalle/equipo-usuarioCREAR',
        ID_TAR_Concenso_Equipo_Usuario_Detalle_Eliminar:        '/informacion-documentada/tareas/consenso/detalle/equipo-usuarioELIMINAR',

        ID_TAR_Concenso_Revision_Detalle:                       '/informacion-documentada/tareas/consenso/detalle/revisiones',
        ID_TAR_Concenso_Revision_Detalle_VISUALIZAR:            '/informacion-documentada/tareas/consenso/detalle/revisionesVISUALIZAR',

        ID_TAR_Aprobacion_Detalle:                              '/informacion-documentada/tareas/aprobacion/detalle',

        ID_TAR_Aprobacion_Detalle_CREAR:                        '/informacion-documentada/tareas/aprobacion/detalleCREAR',
        ID_TAR_Aprobacion_Detalle_VISUALIZAR:                   '/informacion-documentada/tareas/aprobacion/detalleVISUALIZAR',
        ID_TAR_Aprobacion_Detalle_MODIFICAR:                    '/informacion-documentada/tareas/aprobacion/detalleMODIFICAR',
        ID_TAR_Aprobacion_Detalle_ELIMINAR:                     '/informacion-documentada/tareas/aprobacion/detalleELIMINAR',
        
        ID_TAR_Homologacion_Detalle_CREAR:                      '/informacion-documentada/tareas/homologacion/detalleCREAR',
        ID_TAR_Homologacion_Detalle_VISUALIZAR:                 '/informacion-documentada/tareas/homologacion/detalleVISUALIZAR',
        ID_TAR_Homologacion_Detalle_ELIMINAR:                   '/informacion-documentada/tareas/homologacion/detalleELIMINAR',

        ID_TAR_Aprobacion_Documento_Relacionado_Detalle:            '/informacion-documentada/tareas/aprobacion/detalle/documentos-relacionados',
        ID_TAR_Aprobacion_Documento_Relacionado_Detalle_CREAR:      '/informacion-documentada/tareas/aprobacion/detalle/documentos-relacionadosCREAR',
        ID_TAR_Aprobacion_Documento_Relacionado_Detalle_ELIMINAR:   '/informacion-documentada/tareas/aprobacion/detalle/documentos-relacionadosELIMINAR',

        ID_TAR_Homologacion_Documento_Relacionado_Detalle:            '/informacion-documentada/tareas/homologacion/detalle/documentos-relacionados',
        ID_TAR_Homologacion_Documento_Relacionado_Detalle_CREAR:      '/informacion-documentada/tareas/homologacion/detalle/documentos-relacionadosCREAR',
        ID_TAR_Homologacion_Documento_Relacionado_Detalle_ELIMINAR:   '/informacion-documentada/tareas/homologacion/detalle/documentos-relacionadosELIMINAR',

        ID_TAR_Homologacion_Equipo_Usuario_Detalle:                 '/informacion-documentada/tareas/homologacion/detalle/equipo-usuario',
        ID_TAR_Homologacion_Equipo_Usuario_Detalle_CREAR:           '/informacion-documentada/tareas/homologacion/detalle/equipo-usuarioCREAR',
        ID_TAR_Homologacion_Equipo_Usuario_Detalle_ELIMINAR:        '/informacion-documentada/tareas/homologacion/detalle/equipo-usuarioELIMINAR',

        ID_TAR_Homologacion_Revision_Detalle:                           '/informacion-documentada/tareas/homologacion/detalle/revisiones',
        ID_TAR_Homologacion_Revision_Detalle_VISUALIZAR:                '/informacion-documentada/tareas/homologacion/detalle/revisionesVISUALIZAR',
        ID_TAR_Homologacion_Bitacora_Detalle:                           '/informacion-documentada/tareas/homologacion/detalle/bitacora',

        ID_TAR_Aprobacion_Equipo_Usuario_Detalle:               '/informacion-documentada/tareas/aprobacion/detalle/equipo-usuario',
        ID_TAR_Aprobacion_Equipo_Usuario_Detalle_CREAR:         '/informacion-documentada/tareas/aprobacion/detalle/equipo-usuarioCREAR',
        ID_TAR_Aprobacion_Equipo_Usuario_Detalle_ELIMINAR:      '/informacion-documentada/tareas/aprobacion/detalle/equipo-usuarioELIMINAR',

        ID_TAR_Aprobacion_Revisiones_Detalle:                   '/informacion-documentada/tareas/aprobacion/detalle/revisiones',
        ID_TAR_Aprobacion_Revisiones_Detalle_VISUALIZAR:        '/informacion-documentada/tareas/aprobacion/detalle/revisionesVISUALIZAR',

        ID_TAR_Aprobacion_Detalle_Elaboracion:                  '/informacion-documentada/tareas/aprobacion/detalle/elaboracion',
        ID_TAR_Aprobacion_Detalle_Elaboracion_CREAR:            '/informacion-documentada/tareas/aprobacion/detalle/elaboracionCREAR',
        ID_TAR_Aprobacion_Detalle_Elaboracion_MODIFICAR:        '/informacion-documentada/tareas/aprobacion/detalle/elaboracionMODIFICAR',
        ID_TAR_Aprobacion_Detalle_Elaboracion_ELIMINAR:         '/informacion-documentada/tareas/aprobacion/detalle/elaboracionELIMINAR',

        ID_TAR_Aprobacion_Detalle_Concenso:                 '/informacion-documentada/tareas/aprobacion/detalle/consenso',
        ID_TAR_Aprobacion_Detalle_Concenso_CREAR:           '/informacion-documentada/tareas/aprobacion/detalle/consensoCREAR',
        ID_TAR_Aprobacion_Detalle_Concenso_MODIFICAR:       '/informacion-documentada/tareas/aprobacion/detalle/consensoMODIFICAR',
        ID_TAR_Aprobacion_Detalle_Concenso_ELIMINAR:        '/informacion-documentada/tareas/aprobacion/detalle/consensoELIMINAR',

        ID_TAR_Aprobacion_Detalle_Aprobacion:               '/informacion-documentada/tareas/aprobacion/detalle/aprobacion',
        ID_TAR_Aprobacion_Detalle_Aprobacion_CREAR:         '/informacion-documentada/tareas/aprobacion/detalle/aprobacionCREAR',
        ID_TAR_Aprobacion_Detalle_Aprobacion_MODIFICAR:     '/informacion-documentada/tareas/aprobacion/detalle/aprobacionMODIFICAR',
        ID_TAR_Aprobacion_Detalle_Aprobacion_ELIMINAR:      '/informacion-documentada/tareas/aprobacion/detalle/aprobacionELIMINAR',

        ID_TAR_Aprobacion_Detalle_Homologacion:             '/informacion-documentada/tareas/aprobacion/detalle/homologacion',
        ID_TAR_Aprobacion_Detalle_Homologacion_CREAR:       '/informacion-documentada/tareas/aprobacion/detalle/homologacionCREAR',
        ID_TAR_Aprobacion_Detalle_Homologacion_MODIFICAR:   '/informacion-documentada/tareas/aprobacion/detalle/homologacionMODIFICAR',
        ID_TAR_Aprobacion_Detalle_Homologacion_ELIMINAR:    '/informacion-documentada/tareas/aprobacion/detalle/homologacionELIMINAR',

        ID_TAR_Homologacion_Detalle:                        '/informacion-documentada/tareas/homologacion/detalle',
        ID_TAR_Homologacion_Detalle_Elaboracion:            '/informacion-documentada/tareas/homologacion/detalle/elaboracion',
        ID_TAR_Homologacion_Detalle_Elaboracion_ELIMINAR:   '/informacion-documentada/tareas/homologacion/detalle/elaboracionELIMINAR',

        ID_TAR_Homologacion_Detalle_Concenso:           '/informacion-documentada/tareas/homologacion/detalle/consenso',
        ID_TAR_Homologacion_Detalle_Concenso_ELIMINAR:  '/informacion-documentada/tareas/homologacion/detalle/consensoELIMINAR',

        ID_TAR_Homologacion_Detalle_Aprobacion:           '/informacion-documentada/tareas/homologacion/detalle/aprobacion',
        ID_TAR_Homologacion_Detalle_Aprobacion_ELIMINAR:  '/informacion-documentada/tareas/homologacion/detalle/aprobacionELIMINAR',

        ID_TAR_Homologacion_Detalle_Homologacion:           '/informacion-documentada/tareas/homologacion/detalle/homologacion',
        ID_TAR_Homologacion_Detalle_Homologacion_CREAR:     '/informacion-documentada/tareas/homologacion/detalle/homologacionCREAR',
        ID_TAR_Homologacion_Detalle_Homologacion_MODIFICAR: '/informacion-documentada/tareas/homologacion/detalle/homologacionMODIFICAR',
        ID_TAR_Homologacion_Detalle_Homologacion_ELIMINAR:  '/informacion-documentada/tareas/homologacion/detalle/homologacionELIMINAR',

        ID_TAR_AprobacionSolicitudRevision_Detalle:                     '/informacion-documentada/tareas/aprobacion-solicitud-revision/detalle',
        ID_TAR_AprobacionSolicitudRevision_Detalle_CREAR:           '/informacion-documentada/tareas/aprobacion-solicitud-revision/detalleCREAR',
        ID_TAR_AprobacionSolicitudRevision_Detalle_MODIFICAR:       '/informacion-documentada/tareas/aprobacion-solicitud-revision/detalleMODIFICAR',
        ID_TAR_AprobacionSolicitudRevision_Detalle_VISUALIZAR:       '/informacion-documentada/tareas/aprobacion-solicitud-revision/detalleVISUALIZAR',

        ID_TAR_AprobacionSolicitudRevision_Detalle_Elaboracion:         '/informacion-documentada/tareas/aprobacion-solicitud-revision/detalle/elaboracion',
        ID_TAR_AprobacionSolicitudRevision_Detalle_Elaboracion_CREAR:   '/informacion-documentada/tareas/aprobacion-solicitud-revision/detalle/elaboracionCREAR',
        ID_TAR_AprobacionSolicitudRevision_Detalle_Elaboracion_MODIFICAR:   '/informacion-documentada/tareas/aprobacion-solicitud-revision/detalle/elaboracionMODIFICAR',
        ID_TAR_AprobacionSolicitudRevision_Detalle_Elaboracion_ELIMINAR:'/informacion-documentada/tareas/aprobacion-solicitud-revision/detalle/elaboracionELIMINAR',

        ID_TAR_AprobacionSolicitudRevision_Detalle_Consenso:                    '/informacion-documentada/tareas/aprobacion-solicitud-revision/detalle/consenso',
        ID_TAR_AprobacionSolicitudRevision_Detalle_Consenso_CREAR:              '/informacion-documentada/tareas/aprobacion-solicitud-revision/detalle/consensoCREAR',
        ID_TAR_AprobacionSolicitudRevision_Detalle_Consenso_MODIFICAR:              '/informacion-documentada/tareas/aprobacion-solicitud-revision/detalle/consensoMODIFICAR',
        ID_TAR_AprobacionSolicitudRevision_Detalle_Consenso_ELIMINAR:           '/informacion-documentada/tareas/aprobacion-solicitud-revision/detalle/consensoELIMINAR',

        ID_TAR_AprobacionSolicitudRevision_Detalle_Aprobacion:              '/informacion-documentada/tareas/aprobacion-solicitud-revision/detalle/aprobacion',
        ID_TAR_AprobacionSolicitudRevision_Detalle_Aprobacion_CREAR:        '/informacion-documentada/tareas/aprobacion-solicitud-revision/detalle/aprobacionCREAR',
        ID_TAR_AprobacionSolicitudRevision_Detalle_Aprobacion_MODIFICAR:        '/informacion-documentada/tareas/aprobacion-solicitud-revision/detalle/aprobacionMODIFICAR',
        ID_TAR_AprobacionSolicitudRevision_Detalle_Aprobacion_ELIMINAR:     '/informacion-documentada/tareas/aprobacion-solicitud-revision/detalle/aprobacionELIMINAR',

        ID_TAR_AprobacionSolicitudRevision_Detalle_Homologacion:             '/informacion-documentada/tareas/aprobacion-solicitud-revision/detalle/homologacion',
        ID_TAR_AprobacionSolicitudRevision_Detalle_Homologacion_CREAR:       '/informacion-documentada/tareas/aprobacion-solicitud-revision/detalle/homologacionCREAR',
        ID_TAR_AprobacionSolicitudRevision_Detalle_Homologacion_MODIFICAR:       '/informacion-documentada/tareas/aprobacion-solicitud-revision/detalle/homologacionMODIFICAR',
        ID_TAR_AprobacionSolicitudRevision_Detalle_Homologacion_ELIMINAR:    '/informacion-documentada/tareas/aprobacion-solicitud-revision/detalle/homologacionELIMINAR',

        ID_TAR_AprobacionSolicitudRevision_Detalle_Documento_Relacionados:          '/informacion-documentada/tareas/aprobacion-solicitud-revision/detalle/documentos-relacionados',
        ID_TAR_AprobacionSolicitudRevision_Detalle_Documento_Relacionados_CREAR:    '/informacion-documentada/tareas/aprobacion-solicitud-revision/detalle/documentos-relacionadosCREAR',
        ID_TAR_AprobacionSolicitudRevision_Detalle_Documento_Relacionados_ELIMINAR: '/informacion-documentada/tareas/aprobacion-solicitud-revision/detalle/documentos-relacionadosELIMINAR',

        ID_TAR_AprobacionSolicitudRevision_Detalle_Equipo_Usuario:                  '/informacion-documentada/tareas/aprobacion-solicitud-revision/detalle/equipo-usuario',
        ID_TAR_AprobacionSolicitudRevision_Detalle_Equipo_Usuario_CREAR:            '/informacion-documentada/tareas/aprobacion-solicitud-revision/detalle/equipo-usuarioCREAR',
        ID_TAR_AprobacionSolicitudRevision_Detalle_Equipo_Usuario_ELIMINAR:         '/informacion-documentada/tareas/aprobacion-solicitud-revision/detalle/equipo-usuarioELIMINAR',

        ID_TAR_AprobacionSolicitudRevision_Detalle_Revisiones:                  '/informacion-documentada/tareas/aprobacion-solicitud-revision/detalle/revisiones',
        ID_TAR_AprobacionSolicitudRevision_Detalle_Revisiones_VISUALIZAR:       '/informacion-documentada/tareas/aprobacion-solicitud-revision/detalle/revisionesVISUALIZAR',

        ID_TAR_Aprobacion_Copia_Impresa_Detalle:                '/informacion-documentada/tareas/aprobacion-copias-impresas/detalle',
        ID_TAR_Aprobacion_Copia_Impresa_Detalle_CREAR:          '/informacion-documentada/tareas/aprobacion-copias-impresas/detalleCREAR',
        ID_TAR_Aprobacion_Copia_Impresa_Detalle_VISUALIZAR:      '/informacion-documentada/tareas/aprobacion-copias-impresas/detalleVISUALIZAR',
        ID_TAR_Aprobacion_Copia_Impresa_Detalle_ELIMINAR:       '/informacion-documentada/tareas/aprobacion-copias-impresas/detalleELIMINAR',

        ID_TAR_Aprobacion_Copia_Impresa_Detalle_Bitacora:               '/informacion-documentada/tareas/aprobacion-copias-impresas/detalle/bitacora',
        ID_TAR_Aprobacion_Copia_Impresa_Detalle_Bitacora_VISUALIZAR:    '/informacion-documentada/tareas/aprobacion-copias-impresas/detalle/bitacoraVISUALIZAR',

        ID_TAR_Aprobacion_Copia_Impresa_Detalle_Critica:                '/informacion-documentada/tareas/aprobacion-copias-impresas/detalle/critica',
        ID_TAR_Aprobacion_Copia_Impresa_Detalle_Critica_VISUALIZAR:     '/informacion-documentada/tareas/aprobacion-copias-impresas/detalle/criticaVISUALIZAR',

        ID_TAR_Aprobacion_Cancelacion_Detalle:                                '/informacion-documentada/tareas/aprobacion-cancelacion/detalle',
        ID_TAR_Aprobacion_Cancelacion_Detalle_CREAR:                          '/informacion-documentada/tareas/aprobacion-cancelacion/detalleCREAR',
        ID_TAR_Aprobacion_Cancelacion_Detalle_VISUALIZAR:                     '/informacion-documentada/tareas/aprobacion-cancelacion/detalleVISUALIZAR',
        ID_TAR_Aprobacion_Cancelacion_Detalle_MODIFICAR:                      '/informacion-documentada/tareas/aprobacion-cancelacion/detalleMODIFICAR',

        ID_TAR_Aprobacion_Cancelacion_Detalle_Documento_Relacionado:             '/informacion-documentada/tareas/aprobacion-cancelacion/detalle/documentos-relacionados',
        ID_TAR_Aprobacion_Cancelacion_Detalle_Documento_Relacionado_VISUALIZAR:  '/informacion-documentada/tareas/aprobacion-cancelacion/detalle/documentos-relacionadosVISUALIZAR',

        ID_TAR_Aprobacion_Cancelacion_Detalle_Sustento_Solicitudes:                  '/informacion-documentada/tareas/aprobacion-cancelacion/detalle/sustento-solicitudes',
        ID_TAR_Aprobacion_Cancelacion_Detalle_Sustento_Solicitudes_EXPORTAR:       '/informacion-documentada/tareas/aprobacion-cancelacion/detalle/sustento-solicitudesEXPORTAR',
                                                                               
        ID_TAR_Cancelacion_Documento_Detalle:                               '/informacion-documentada/tareas/cancelacion-documentos/detalle',
        ID_TAR_Cancelacion_Documento_Detalle_CREAR:                         '/informacion-documentada/tareas/cancelacion-documentos/detalleCREAR',
        ID_TAR_Cancelacion_Documento_Detalle_VISUALIZAR:                    '/informacion-documentada/tareas/cancelacion-documentos/detalleVISUALIZAR',

        ID_TAR_Cancelacion_Documento_Detalle_Documento_Relacionado:             '/informacion-documentada/tareas/cancelacion-documentos/detalle/documentos-relacionados',
        ID_TAR_Cancelacion_Documento_Detalle_Documento_Relacionado_VISUALIZAR:  '/informacion-documentada/tareas/cancelacion-documentos/detalle/documentos-relacionadosVISUALIZAR',

        ID_TAR_Cancelacion_Documento_Detalle_Sustento_Solicitud:               '/informacion-documentada/tareas/cancelacion-documentos/detalle/sustento-solicitudes',
        ID_TAR_Cancelacion_Documento_Detalle_Sustento_Solicitud_VISUALIZAR:    '/informacion-documentada/tareas/cancelacion-documentos/detalle/sustento-solicitudesVISUALIZAR',

        ID_REV_ACT_DOC_Programacion_Detalle:                    '/informacion-documentada/revision-actualizacion/programacion/detalle',
        ID_REV_ACT_DOC_Programacion_Detalle_CREAR:              '/informacion-documentada/revision-actualizacion/programacion/detalleCREAR',
        ID_REV_ACT_DOC_Programacion_Detalle_VISUALIZAR:         '/informacion-documentada/revision-actualizacion/programacion/detalleVISUALIZAR',

        ID_REV_ACT_DOC_Distribucion_Ejecucion_Detalle:              '/informacion-documentada/revision-actualizacion/distribucion-ejecucion/detalle',
        ID_REV_ACT_DOC_Distribucion_Ejecucion_Detalle_CREAR:        '/informacion-documentada/revision-actualizacion/distribucion-ejecucion/detalleCREAR',
        ID_REV_ACT_DOC_Distribucion_Ejecucion_Detalle_MODIFICAR:    '/informacion-documentada/revision-actualizacion/distribucion-ejecucion/detalleMODIFICAR',


        ID_CON_DescargaVideosPlantillas_Detalle:                '/informacion-documentada/consulta/descarga-videos-plantillas/detalle',
        ID_CON_DescargaVideosPlantillas_Detalle_CREAR:          '/informacion-documentada/consulta/descarga-videos-plantillas/detalleCREAR',
        ID_CON_DescargaVideosPlantillas_Detalle_EXPORTAR:       '/informacion-documentada/consulta/descarga-videos-plantillas/detalleEXPORTAR',
};

export const RutaConstantes = {
    Starterview:                                    '/starterview',
    ConsultaGeneral:                                '/documento/general/revisardocumentos',
    ConsultaPorJerarquia:                           '/documento/general/bandejadocumento',
    EditarConsultaPorJerarquia:                     '/documento/general/bandejadocumento/editar',
    RegistroBusquedaDocumento:                      '/documento/general/bandejadocumento/editar/registrar-documento',
    CON_BandejaSeguimiento:                         '/consulta/descarga/seguimientoDocumento',
    StarterviewAuditoria:                           '/start-auditoria',
    StarterviewNoConformidad:                       '/start-noconformidad',
    StarterviewCapacitacion:                        '/start-capacitacion',
    StarterviewMantenimiento:                       '/start-mantenimiento'



                                                    
}