export enum Constante {
    ETAPA_RUTA              = "Listado de Etapas de Ruta (Fases del Documento)",
    ETAPA_RUTA_ELABORACION  = 'ELABORACION',
    ETAPA_RUTA_CONSENSO     = 'CONSENSO',
    ETAPA_RUTA_APROBACION   = 'APROBACION',
    ETAPA_RUTA_HOMOLOGACION = 'HOMOLOGACION',
    TIPO_JERARQUIA          = "Listado de Tipo de Jerarquia",
    TIPO_JERARQUIA_PROCESO  = "PROCESO",
    TIPO_JERARQUIA_ALCANCE  = "ALCANCE",
    TIPO_JERARQUIA_GERENCIA = "GERENCIA",
    TITULO_PROCESO          = "Proceso",
    TITULO_ALCANCE          = "Alcance",
    TITULO_GERENCIA         = "Gerencia",
    TIPO_DOCUMENTO          = "Listado de Tipo de Documento",
    TIPO_DOCUMENTO_COMPL    = 'Listado de Tipos de Documentos Complementarios',
    ESTADO_DOCUMENTO        = "Listado de Estado de Documento",
    ESTADO_DOCUENTO_EMISION = "EMISION",
    FASE_ACT_DOCUMENTO      = "Listado de Etapas de Ruta (Fases del Documento)",
    ESTADO_FASE_ACT_DOC     = "Listado de Estado de la Fase Actual",
    ESTADO_MOTIVO_REVIS     = "Listado de Motivo de Revision",
    LISTA_AUDITORES= "Listado Rol de Auditores",
    LISTA_TRIMESTRE           = "Listado de Trimestre",
    TRIMESTRE_I               = "I",
    TRIMESTRE_II              = "II",
    TRIMESTRE_III             = "III",
    TRIMESTRE_IV              = "IV",
    TIPO_FECHA_NO_CONFORMIDAD = "Listado de Fechas",
    TIPO_NO_CONFORMIDAD        = "Listado de tipo de No Conformidad",
    TIPO_ORIGEN_DETECCION      = 'Listado de Origen de Deteccion',
    TIPO_AREA_GERENCIA         = 'G',
    TIPO_MOTIVO_IMPRESION ="Listado de Motivos para Impresion",
    TIPO_COPIA                 ="Listado de Tipo de Copia",
    SEDE                        ="Listado de Sedes",
    TIPO_AREA_EQUIPO           = 'E',
    ETAPA_IDENTIF_PROBLEMA      = 'Identificacion del Problema',
    ETAPA_OBS_ANALISIS          = 'Observacion y Analisis',
    ETAPA_PLAN_ACCION           = 'Plan de Accion',
    ETAPA_EJECUCION             = 'Ejecucion',
    ETAPA_VERIF_ESTAND          = 'Verificacion y Estandarizacion',
    ETAPA_CIERRE                = 'Cierre',
    ESTADO_SOLICITUD        = "Listado de Estado de la Solicitud",
    PLAZOS                  = 'Listado de Plazos',
	PLAZO_SUPERIOR               = 'Limite Superior',
    PLAZO_INFERIOR               = 'Limite Inferior',
    PLAZO_APROBACION             = 'Plazo Fecha de Aprobacion',
    LISTA_PLANTILLA_DOCUMENTOS ="Listado de Tipo de Video o Plantilla",
    LISTA_PLANTILLA_AUDITORIA ="Listado de Tipo de Video o Plantilla Auditoria",
    LISTA_PLANTILLA_NO_CONFORMIDAD ="Listado de Tipo de Video o Plantilla No Conformidad",
    LISTA_PLANTILLA_CAPACITACION ="Listado de Tipo de Video o Plantilla Capacitacion",
    ESTADO_SOLICITUD_EMITIDO     = 'Emitido',
    ESTADO_SOLICITUD_RECHAZADO   = 'Rechazado',
    ESTADO_SOLICITUD_APROBADO    = 'Aprobado',
    ESTADO_DOCUMENTO_EMISION     = 'Emision',
    ESTADO_DOCUMENTO_CANCELADO   = 'Cancelado',
    ESTADO_DOCUMENTO_EN_REVISION = 'En Revision',
    ESTADO_DOCUMENTO_APROBADO    = 'Aprobado',
	ESTADO_PROGRAMACION          = 'Listado de Estado de la Programacion',
    ESTADO_EJECUCION             = 'Listado de Estado de la Ejecucion',
	INDICADOR_FASE_GUARDAR       = '1',
    INDICADOR_FASE_APROBAR       = '2',
    INDICADOR_FASE_RECHAZAR      = '3',
	// YPM - INICIO
    TIPO_PROCESO                 = 'Listado de Tipo de Proceso',
    NIVEL_PROCESO                = 'Listado de Nivel de Proceso',
    MODULOS_SISTEMA              = 'Listado de Modulos del Sistema',
    INFORMACION_DOCUMENTADA      = 'Información Documentada',
    MANTENIMIENTO                = 'Mantenimiento',
    ESTADO_SOLICITUD_EN_REVISION = '141',
    //ESTADO_SOLICITUD_RECHAZADO   =  '142',
    // YPM - FIN
    TIPO_JERARQUIA_SIN_ALCANCE   = 'SIN ALCANCE',
    CORREO_REGISTRO_SOLICITUD    = 'ENVIO DE NOTIFICACION DE REGISTRO DE SOLICITUD DE REVISION',
    CORREO_MODIFICAR             = 'ENVIO DE NOTIFICACION DE MODIFICACION DE DATOS',
    CORREO_APROBAR_SOLICITUD     = 'NOTIFICAR LA APROBACION DE SOLICITUD DE REVISION DE DOCUMENTO',
    CORREO_PLAZO_ATENCION        = 'NOTIFICACION DE PLAZO DE ATENCION',
    CORREO_RECHAZO_DOCUMENTO     = 'NOTIFICACION DE RECHAZO DE DOCUMENTO',
    CORREO_DOCUMENTO_LIBERADO    = 'NOTIFICACION DE DOCUMENTO LIBERADO',
    CORREO_SOLICITUD_COPIA       = 'ENVIO DE NOTIFICACION DE SOLICITUD DE COPIA IMPRESA',
    CORREO_IMPRESION             = 'NOTIFICACION POR IMPRESION DE DOCUMENTO',
    CORREO_IMPRESION_RECHAZO     = 'NOTIFICACION DE RECHAZO DE COPIA IMPRESA',    
    CORREO_REGISTRO_CANCELACION  = 'ENVIO DE NOTIFICACION DE REGISTRO DE SOLICITUD DE CANCELACION DE DOCUMENTO',
    CORREO_APROBAR_CANCELACION   = 'ENVIO DE NOTIFICACION DE APROBACION DE LA SOLICITUD DE CANCELACION DEL DOCUMENTO',
    CORREO_EJECUTAR_CANCELACION  = 'ENVIO DE NOTIFICACION DE LA EJECUCCION DE LA CANCELACION DEL DOCUMENTO',
    CORREO_REGISTRO_PROGRAMACION = 'ENVIO DE NOTIFICACION DE PROGRAMACION DEL PROCESO DE REVISION Y ACTUALIZACION DE DOCUMENTOS',
    CORREO_DISTRIBUIR_PROGRAMACION='ENVIO DE NOTIFICACION DE LA DISTRIBUCION DEL PROCESO DE REVISION Y ACTUALIZACION DE DOCUMENTOS',
    CORREO_EJECUTAR_PROGRAMACION = 'ENVIO DE NOTIFICACION DE LA EJECUCION DEL PROCESO DE REVISION Y ACTUALIZACION DE DOCUMENTOS',
    CORREO_APROBACION            = 'NOTIFICAR LA APROBACION DE REVISION',
    CORREO_RECHAZO_CANCELACION   = 'ENVIO DE NOTIFICACION DE RECHAZO DE LA CANCELACION DEL DOCUMENTO',

    ESTADO_FASE_ACT_DOC_PENDIENTE = 'Pendiente',
    ESTADO_FASE_ACT_DOC_RECHAZADO = 'Rechazado',
    ESTADO_FASE_ACT_DOC_APROBADO  = 'Aprobado',
    ESTADO_FASE_ACT_DOC_CANCELADO = 'Cancelado',

    ID_ESTADO_PROGRAMACION_PROGRAMADO      = '150',
    ID_ESTADO_PROGRAMACION_DISTRIBUIDO      = '151',
    ID_ESTADO_PROGRAMACION_EJECUTADO      = '152',
    ID_ESTADO_REVISION_REVISADO  = "158",
    ID_ESTADO_REVISION_CANCELADO = "159",

    ID_TIPO_COPIA_CONTROLADA = "114",
    ID_TIPO_COPIA_NO_CONTROLADA = "115"


}


